### PR TITLE
Feat: Question Practice Suite

### PR DESCRIPTION
**Pull request by gnaaruag**
### Features
- Pick questions based on difficulty
- Search particular question based on name or topic
- Pick Random question 
- Estimate time to solve question

Additionally
- difficulty and estimate time now show up on admin question edit
- Added documentation to validate submission function (reference)

Co-authored-by: Srija-C2 <128138613+SrijaC2@users.noreply.github.com>

### CODE REVIEW

**Review by Sankeerth-g7 — CHANGES_REQUESTED** [review]
The code looks well-structured and functional overall. However, I noticed that the `courseId` variable will be received as undefined, which subsequently affects the `participationId` field. While this issue doesn't seem to impact the core functionality of the pull request, it's important to ensure all variables are properly initialized. Additionally, I recommend removing any unnecessary console logs for cleaner code. Please verify and address these points accordingly. For reference, please see `Server/index.js` line 334. Thank you!

**Comment by gnaaruag** [comment]
> The code looks well-structured and functional overall. However, I noticed that the `courseId` variable will be received as undefined, which subsequently affects the `participationId` field. While this issue doesn't seem to impact the core functionality of the pull request, it's important to ensure all variables are properly initialized. Additionally, I recommend removing any unnecessary console logs for cleaner code. Please verify and address these points accordingly. For reference, please see `Server/index.js` line 334. Thank you!

all necessary changes have been made as specified

**Review by Sankeerth-g7 — APPROVED** [review]
I am proceed with merging the pull request. However, I'd like to note that while the functionality is now working as expected I think that no provision has been made to store data for generating reports in the future. anyways well done 👍

**Comment by gnaaruag** [comment]
> I am proceed with merging the pull request. However, I'd like to note that while the functionality is now working as expected I think that no provision has been made to store data for generating reports in the future. anyways well done 👍

will work on it in a future pr

**Pull request merged**
